"""Initial migration

Revision ID: 0bd2fc2cbceb
Revises: 
Create Date: 2026-01-09 00:20:38.453848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd2fc2cbceb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование счета'),
    sa.Column('details', sa.String(), nullable=True, comment='Дополнительная информация о счете'),
    sa.Column('account_number', sa.String(length=100), nullable=True, comment='Номер счета'),
    sa.Column('account_type', sa.String(length=50), nullable=False, comment='Тип счета'),
    sa.Column('currency', sa.String(length=4), nullable=False, comment='Валюта счета (код ISO 4217)'),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False, comment='Текущий остаток на счете'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник счетов организации (банковские, кассовые и прочие счета)'
    )
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Наименование разрешения'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Системный код разрешения'),
    sa.Column('resource', sa.String(length=50), nullable=False, comment='Ресурс системы (системный список)'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Действие с ресурсом (системный список)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание разрешения'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Разрешения на выполнение действий с ресурсами системы'
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование номенклатуры'),
    sa.Column('sku', sa.String(length=50), nullable=False, comment='Артикул (уникальный код товара)'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='Описание номенклатуры'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Единица измерения (системный список)'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник номенклатуры (товары и продукция)'
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Наименование роли'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Системный код роли'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание роли и её назначения'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Роли пользователей для управления доступом (RBAC)'
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False, comment='Email пользователя (для входа в систему)'),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False, comment='Хэшированный пароль'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активность пользователя (может входить в систему)'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Признак суперпользователя (полный доступ)'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Подтверждение email пользователя'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Фамилия пользователя'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Телефон пользователя'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Пользователи системы'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('warehouses',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование склада'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Код склада'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='Адрес местонахождения склада'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Признак активности склада'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Справочник складов организации'
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_table('movements',
    sa.Column('movement_number', sa.String(length=50), nullable=False, comment='Номер документа перемещения'),
    sa.Column('from_warehouse_id', sa.Integer(), nullable=False, comment='Склад отправитель'),
    sa.Column('to_warehouse_id', sa.Integer(), nullable=False, comment='Склад получатель'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус документа (системный список)'),
    sa.Column('planned_date', sa.DateTime(), nullable=True, comment='Плановая дата перемещения'),
    sa.Column('completed_date', sa.DateTime(), nullable=True, comment='Фактическая дата завершения перемещения'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouses.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Документы перемещения товаров между складами'
    )
    op.create_index(op.f('ix_movements_id'), 'movements', ['id'], unique=False)
    op.create_index(op.f('ix_movements_movement_number'), 'movements', ['movement_number'], unique=True)
    op.create_index(op.f('ix_movements_status'), 'movements', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('order_number', sa.String(length=50), nullable=False, comment='Номер заказа на производство'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Идентификатор производимой номенклатуры'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='Количество к производству'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Статус заказа (системный список)'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Заказы клиентов'
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Идентификатор роли'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='Идентификатор разрешения'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    comment='Связь ролей с разрешениями (многие ко многим)'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='Идентификатор роли'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    comment='Связь пользователей с ролями (многие ко многим)'
    )
    op.create_table('warehouse_items',
    sa.Column('warehouse_id', sa.Integer(), nullable=False, comment='Идентификатор склада'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Идентификатор номенклатуры'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Количество в наличии'),
    sa.Column('reserved_quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Зарезервированное количество'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Остатки товаров на складах'
    )
    op.create_index(op.f('ix_warehouse_items_id'), 'warehouse_items', ['id'], unique=False)
    op.create_index(op.f('ix_warehouse_items_product_id'), 'warehouse_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_warehouse_items_warehouse_id'), 'warehouse_items', ['warehouse_id'], unique=False)
    op.create_table('movement_items',
    sa.Column('movement_id', sa.Integer(), nullable=False, comment='Идентификатор документа перемещения'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Идентификатор номенклатуры'),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False, comment='Количество к перемещению'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Позиции документа перемещения (табличная часть)'
    )
    op.create_index(op.f('ix_movement_items_id'), 'movement_items', ['id'], unique=False)
    op.create_index(op.f('ix_movement_items_movement_id'), 'movement_items', ['movement_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_number', sa.String(length=50), nullable=False, comment='Номер финансовой операции'),
    sa.Column('transaction_type', sa.String(length=20), nullable=False, comment='Тип операции (системный список)'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Категория операции (системный список)'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Сумма операции'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Валюта операции (код ISO 4217)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание финансовой операции'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='Дата совершения операции'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='Связь с заказом'),
    sa.Column('movement_id', sa.Integer(), nullable=True, comment='Связь с документом перемещения'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Финансовые операции организации'
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_number'), 'transactions', ['transaction_number'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_movement_items_movement_id'), table_name='movement_items')
    op.drop_index(op.f('ix_movement_items_id'), table_name='movement_items')
    op.drop_table('movement_items')
    op.drop_index(op.f('ix_warehouse_items_warehouse_id'), table_name='warehouse_items')
    op.drop_index(op.f('ix_warehouse_items_product_id'), table_name='warehouse_items')
    op.drop_index(op.f('ix_warehouse_items_id'), table_name='warehouse_items')
    op.drop_table('warehouse_items')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_movements_status'), table_name='movements')
    op.drop_index(op.f('ix_movements_movement_number'), table_name='movements')
    op.drop_index(op.f('ix_movements_id'), table_name='movements')
    op.drop_table('movements')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
