"""add operational finance tables

Revision ID: 873ff3370d8d
Revises: 0bd2fc2cbceb
Create Date: 2026-01-09 22:37:11.565872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '873ff3370d8d'
down_revision: Union[str, Sequence[str], None] = '0bd2fc2cbceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_accounts',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование счета'),
    sa.Column('details', sa.String(), nullable=True, comment='Дополнительная информация о счете'),
    sa.Column('account_number', sa.String(length=100), nullable=True, comment='Номер счета'),
    sa.Column('account_type', sa.Enum('CASH', 'NON_CASH', name='operationalaccounttype'), nullable=False, comment='Тип счета (наличный/безналичный)'),
    sa.Column('currency', sa.String(length=4), nullable=False, comment='Валюта счета (код ISO 4217)'),
    sa.Column('start_balance', sa.Numeric(precision=12, scale=2), nullable=False, comment='Начальный остаток на счете'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Признак активности счета'),
    sa.Column('text_color', sa.String(length=7), nullable=True, comment='Цвет текста для визуального отображения (HEX)'),
    sa.Column('bg_color', sa.String(length=7), nullable=True, comment='Цвет фона для визуального отображения (HEX)'),
    sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция сортировки'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Операционные счета организации'
    )
    op.create_index(op.f('ix_operational_accounts_account_number'), 'operational_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_operational_accounts_id'), 'operational_accounts', ['id'], unique=False)
    op.create_table('operational_categories',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Наименование категории'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание категории'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='Иконка для UI'),
    sa.Column('text_color', sa.String(length=7), nullable=True, comment='Цвет текста для визуального отображения (HEX)'),
    sa.Column('bg_color', sa.String(length=7), nullable=True, comment='Цвет фона для визуального отображения (HEX)'),
    sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция сортировки'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Признак активности категории'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Системная категория (не удаляемая)'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Операционный справочник категорий финансовых транзакций'
    )
    op.create_index(op.f('ix_operational_categories_id'), 'operational_categories', ['id'], unique=False)
    op.create_table('operational_category_tree',
    sa.Column('parent_category_id', sa.Integer(), nullable=True, comment='Родительская категория'),
    sa.Column('child_category_id', sa.Integer(), nullable=False, comment='Дочерняя категория'),
    sa.Column('level', sa.Integer(), nullable=False, comment='Уровень вложенности'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'),
    sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'),
    sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'),
    sa.ForeignKeyConstraint(['child_category_id'], ['operational_categories.id'], ),
    sa.ForeignKeyConstraint(['parent_category_id'], ['operational_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Иерархическая структура операционных категорий'
    )
    op.create_index(op.f('ix_operational_category_tree_child_category_id'), 'operational_category_tree', ['child_category_id'], unique=False)
    op.create_index(op.f('ix_operational_category_tree_id'), 'operational_category_tree', ['id'], unique=False)
    op.create_index(op.f('ix_operational_category_tree_parent_category_id'), 'operational_category_tree', ['parent_category_id'], unique=False)
    op.create_table('operational_transactions',
    sa.Column('transaction_number', sa.String(length=50), nullable=False, comment='Номер финансовой операции'),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', name='operationaltransactiontype'), nullable=False, comment='Тип операции'),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELLED', 'PENDING', name='operationaltransactionstatus'), nullable=False, comment='Статус операции'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Сумма операции'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Валюта операции (код ISO 4217)'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Описание финансовой операции'),
    sa.Column('comment', sa.String(length=500), nullable=True, comment='Автоматический комментарий (переводы, системные операции)'),
    sa.Column('transaction_date', sa.Date(), nullable=False, comment='Дата совершения операции'),
    sa.Column('account_id', sa.Integer(), nullable=False, comment='Счет организации'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='Категория операции'),
    sa.Column('related_transaction_id', sa.Integer(), nullable=True, comment='Связанная транзакция (для переводов)'),
    sa.Column('order_id', sa.Integer(), nullable=True, comment='Связь с заказом'),
    sa.Column('movement_id', sa.Integer(), nullable=True, comment='Связь с документом перемещения'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'),
    sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'),
    sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'),
    sa.ForeignKeyConstraint(['account_id'], ['operational_accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['operational_categories.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['operational_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Операционные финансовые операции организации'
    )
    op.create_index(op.f('ix_operational_transactions_account_id'), 'operational_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_operational_transactions_category_id'), 'operational_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_operational_transactions_id'), 'operational_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_operational_transactions_related_transaction_id'), 'operational_transactions', ['related_transaction_id'], unique=False)
    op.create_index(op.f('ix_operational_transactions_status'), 'operational_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_operational_transactions_transaction_date'), 'operational_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_operational_transactions_transaction_number'), 'operational_transactions', ['transaction_number'], unique=True)
    op.create_index(op.f('ix_operational_transactions_transaction_type'), 'operational_transactions', ['transaction_type'], unique=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_number'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_accounts_account_number'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.add_column('movement_items', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('movement_items', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('movement_items', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    op.add_column('movements', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('movements', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('movements', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    op.add_column('orders', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('orders', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('orders', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    op.add_column('permissions', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('permissions', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('permissions', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    op.create_table_comment(
        'permissions',
        'Разрешения на выполнение действий в системе',
        existing_comment='Разрешения на выполнение действий с ресурсами системы',
        schema=None
    )
    op.add_column('products', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('products', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('products', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    op.add_column('roles', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('roles', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('roles', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    op.add_column('users', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('users', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('users', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    op.add_column('warehouse_items', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('warehouse_items', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('warehouse_items', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    op.add_column('warehouses', sa.Column('text_color', sa.String(length=20), nullable=True, comment='Цвет текста для UI (hex код)'))
    op.add_column('warehouses', sa.Column('bg_color', sa.String(length=20), nullable=True, comment='Цвет фона для UI (hex код)'))
    op.add_column('warehouses', sa.Column('sort_position', sa.Integer(), nullable=True, comment='Позиция при сортировке'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warehouses', 'sort_position')
    op.drop_column('warehouses', 'bg_color')
    op.drop_column('warehouses', 'text_color')
    op.drop_column('warehouse_items', 'sort_position')
    op.drop_column('warehouse_items', 'bg_color')
    op.drop_column('warehouse_items', 'text_color')
    op.drop_column('users', 'sort_position')
    op.drop_column('users', 'bg_color')
    op.drop_column('users', 'text_color')
    op.drop_column('roles', 'sort_position')
    op.drop_column('roles', 'bg_color')
    op.drop_column('roles', 'text_color')
    op.drop_column('products', 'sort_position')
    op.drop_column('products', 'bg_color')
    op.drop_column('products', 'text_color')
    op.create_table_comment(
        'permissions',
        'Разрешения на выполнение действий с ресурсами системы',
        existing_comment='Разрешения на выполнение действий в системе',
        schema=None
    )
    op.drop_column('permissions', 'sort_position')
    op.drop_column('permissions', 'bg_color')
    op.drop_column('permissions', 'text_color')
    op.drop_column('orders', 'sort_position')
    op.drop_column('orders', 'bg_color')
    op.drop_column('orders', 'text_color')
    op.drop_column('movements', 'sort_position')
    op.drop_column('movements', 'bg_color')
    op.drop_column('movements', 'text_color')
    op.drop_column('movement_items', 'sort_position')
    op.drop_column('movement_items', 'bg_color')
    op.drop_column('movement_items', 'text_color')
    op.create_table('accounts',
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='Наименование счета'),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Дополнительная информация о счете'),
    sa.Column('account_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Номер счета'),
    sa.Column('account_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Тип счета'),
    sa.Column('currency', sa.VARCHAR(length=4), autoincrement=False, nullable=False, comment='Валюта счета (код ISO 4217)'),
    sa.Column('balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, comment='Текущий остаток на счете'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey')),
    comment='Справочник счетов организации (банковские, кассовые и прочие счета)'
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_account_number'), 'accounts', ['account_number'], unique=True)
    op.create_table('transactions',
    sa.Column('transaction_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Номер финансовой операции'),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='Тип операции (системный список)'),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Категория операции (системный список)'),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False, comment='Сумма операции'),
    sa.Column('currency', sa.VARCHAR(length=3), autoincrement=False, nullable=False, comment='Валюта операции (код ISO 4217)'),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True, comment='Описание финансовой операции'),
    sa.Column('transaction_date', sa.DATE(), autoincrement=False, nullable=False, comment='Дата совершения операции'),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Связь с заказом'),
    sa.Column('movement_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Связь с документом перемещения'),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Уникальный идентификатор записи'),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Дата и время последнего изменения записи'),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Признак удаления записи (мягкое удаление)'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], name=op.f('transactions_movement_id_fkey')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('transactions_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey')),
    comment='Финансовые операции организации'
    )
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_number'), 'transactions', ['transaction_number'], unique=True)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_operational_transactions_transaction_type'), table_name='operational_transactions')
    op.drop_index(op.f('ix_operational_transactions_transaction_number'), table_name='operational_transactions')
    op.drop_index(op.f('ix_operational_transactions_transaction_date'), table_name='operational_transactions')
    op.drop_index(op.f('ix_operational_transactions_status'), table_name='operational_transactions')
    op.drop_index(op.f('ix_operational_transactions_related_transaction_id'), table_name='operational_transactions')
    op.drop_index(op.f('ix_operational_transactions_id'), table_name='operational_transactions')
    op.drop_index(op.f('ix_operational_transactions_category_id'), table_name='operational_transactions')
    op.drop_index(op.f('ix_operational_transactions_account_id'), table_name='operational_transactions')
    op.drop_table('operational_transactions')
    op.drop_index(op.f('ix_operational_category_tree_parent_category_id'), table_name='operational_category_tree')
    op.drop_index(op.f('ix_operational_category_tree_id'), table_name='operational_category_tree')
    op.drop_index(op.f('ix_operational_category_tree_child_category_id'), table_name='operational_category_tree')
    op.drop_table('operational_category_tree')
    op.drop_index(op.f('ix_operational_categories_id'), table_name='operational_categories')
    op.drop_table('operational_categories')
    op.drop_index(op.f('ix_operational_accounts_id'), table_name='operational_accounts')
    op.drop_index(op.f('ix_operational_accounts_account_number'), table_name='operational_accounts')
    op.drop_table('operational_accounts')
    # ### end Alembic commands ###
